
'------------------------------------------------------------------------------
' <auto-generated>
'    Этот код был создан из шаблона.
'
'    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("94efa5bb-f952-469a-868c-b8b73badf1d1")>
#Region "Контексты"

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
Public Partial Class ExampleEntities
    Inherits ObjectContext

    #Region "Конструкторы"

    ''' <summary>
    ''' Инициализирует новый объект ExampleEntities, используя строку соединения из раздела "ExampleEntities" файла конфигурации приложения.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=ExampleEntities", "ExampleEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализация нового объекта ExampleEntities.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "ExampleEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Инициализация нового объекта ExampleEntities.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "ExampleEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Разделяемые методы"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Свойства ObjectSet"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property Messages() As ObjectSet(Of Messages)
        Get
            If (_Messages Is Nothing) Then
                _Messages = MyBase.CreateObjectSet(Of Messages)("Messages")
            End If
            Return _Messages
        End Get
    End Property

    Private _Messages As ObjectSet(Of Messages)

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    Public ReadOnly Property Users() As ObjectSet(Of Users)
        Get
            If (_Users Is Nothing) Then
                _Users = MyBase.CreateObjectSet(Of Users)("Users")
            End If
            Return _Users
        End Get
    End Property

    Private _Users As ObjectSet(Of Users)

    #End Region

    #Region "Методы AddTo"

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet Messages. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToMessages(ByVal messages As Messages)
        MyBase.AddObject("Messages", messages)
    End Sub

    ''' <summary>
    ''' Устаревший метод для добавления новых объектов в набор EntitySet Users. Взамен можно использовать метод .Add связанного свойства ObjectSet(Of T).
    ''' </summary>
    Public Sub AddToUsers(ByVal users As Users)
        MyBase.AddObject("Users", users)
    End Sub

    #End Region

End Class

#End Region

#Region "Сущности"

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ExampleModel", Name:="Messages")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Messages
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта Messages.
    ''' </summary>
    ''' <param name="id">Исходное значение свойства Id.</param>
    ''' <param name="userId">Исходное значение свойства UserId.</param>
    Public Shared Function CreateMessages(id As Global.System.Guid, userId As Global.System.Guid) As Messages
        Dim messages as Messages = New Messages
        messages.Id = id
        messages.UserId = userId
        Return messages
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property MainText() As Global.System.String
        Get
            Return _MainText
        End Get
        Set
            OnMainTextChanging(value)
            ReportPropertyChanging("MainText")
            _MainText = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("MainText")
            OnMainTextChanged()
        End Set
    End Property

    Private _MainText As Global.System.String
    Private Partial Sub OnMainTextChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMainTextChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateCreated() As Nullable(Of Global.System.DateTime)
        Get
            Return _DateCreated
        End Get
        Set
            OnDateCreatedChanging(value)
            ReportPropertyChanging("DateCreated")
            _DateCreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateCreated")
            OnDateCreatedChanged()
        End Set
    End Property

    Private _DateCreated As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDateCreatedChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDateCreatedChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Guid
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Guid
    Private Partial Sub OnIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property UserId() As Global.System.Guid
        Get
            Return _UserId
        End Get
        Set
            OnUserIdChanging(value)
            ReportPropertyChanging("UserId")
            _UserId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserId")
            OnUserIdChanged()
        End Set
    End Property

    Private _UserId As Global.System.Guid
    Private Partial Sub OnUserIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnUserIdChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' Нет доступной документации по метаданным.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="ExampleModel", Name:="Users")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Users
    Inherits EntityObject
    #Region "Фабричный метод"

    ''' <summary>
    ''' Создание нового объекта Users.
    ''' </summary>
    ''' <param name="id">Исходное значение свойства Id.</param>
    Public Shared Function CreateUsers(id As Global.System.Guid) As Users
        Dim users as Users = New Users
        users.Id = id
        Return users
    End Function

    #End Region

    #Region "Свойства-примитивы"

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserName() As Global.System.String
        Get
            Return _UserName
        End Get
        Set
            OnUserNameChanging(value)
            ReportPropertyChanging("UserName")
            _UserName = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UserName")
            OnUserNameChanged()
        End Set
    End Property

    Private _UserName As Global.System.String
    Private Partial Sub OnUserNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserNameChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserEmail() As Global.System.String
        Get
            Return _UserEmail
        End Get
        Set
            OnUserEmailChanging(value)
            ReportPropertyChanging("UserEmail")
            _UserEmail = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("UserEmail")
            OnUserEmailChanged()
        End Set
    End Property

    Private _UserEmail As Global.System.String
    Private Partial Sub OnUserEmailChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserEmailChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DateCreated() As Nullable(Of Global.System.DateTime)
        Get
            Return _DateCreated
        End Get
        Set
            OnDateCreatedChanging(value)
            ReportPropertyChanging("DateCreated")
            _DateCreated = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DateCreated")
            OnDateCreatedChanged()
        End Set
    End Property

    Private _DateCreated As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDateCreatedChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDateCreatedChanged()
    End Sub

    ''' <summary>
    ''' Нет доступной документации по метаданным.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Guid
        Get
            Return _Id
        End Get
        Set
            If (_Id <> Value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property

    Private _Id As Global.System.Guid
    Private Partial Sub OnIdChanging(value As Global.System.Guid)
    End Sub

    Private Partial Sub OnIdChanged()
    End Sub

    #End Region

End Class

#End Region


